### ISSUE TITLE
Linux support for FileX::is_read_only() function

### ISSUE THREAD

**Issue by Gravecat** [Gravecat/Greave#11]
Is this suggestion a new idea, or a change to an existing system?
-----------------------------------------------------------------
An enhancement to an existing function.

What did you have in mind?
--------------------------
The functiion `is_read_only()` in [core/filex.cpp](https://github.com/Gravecat/Greave/blob/main/src/core/filex.cpp) takes a filename as a parameter, and checks if the file is set to read-only on the filesystem. The problem is, currently it only works on Windows (using a call to `GetFileAttributes` from `windows.h`), and will always return false on non-Windows platforms.

Ideally, this function should be able to check if a file is read-only on non-Windows platforms (i.e. Linux).

Any other comments?
-------------------
It seems like it'd be a fairly simple fix, but I'm not personally familiar with dealing with file-system code in Linux, so I'm hoping someone reading this will know a good way to solve the problem.

**Comment by Hunajpu** [comment]
Hi! I would like to help with this

**Comment by Gravecat** [comment]
Sure thing, @Hunajpu! Any help would be appreciated. :)

**Comment by Gravecat** [comment]
Looks like that did the trick! Thanks for the help! :)
