### ISSUE TITLE
Xwindows keyboard input not matching layout

### ISSUE THREAD

**Issue by BeerFox** [Gravecat/Greave#24]
When running Greave using Xwindows on a system with a keymap set to something other than qwerty, the game uses qwerty keymappings instead of the system selection. For example, on a system with the keymapping set to Dvorak, at the 'type quit to exit' screen the keystrokes come out 'xfgk'.

Other Xwin applications on the same system don't show the issue, and the curses terminal also works correctly.

**Comment by Gravecat** [comment]
Looks like the attempted fix worked, this bug's now patched in the dev builds. As always, this fix will be included in the next prealpha release build (0.0A4). :3
