### ISSUE TITLE
Entering ridiculously high numbers into #money command causes a crash.

### ISSUE THREAD

**Issue by Gravecat** [Gravecat/Greave#6]
This is both a simple and not-so-simple issue. The problem is caused by std::stol() in core/parser.cpp, because std::stol() does not like being given invalid numbers (i.e. numbers way outside of its range).

Ideally, I'd want to replace *any and all* processing of user-inputted numbers with some sort of overflow-safe, custom string-to-integer functions (I guess in core/strx.cpp), something that'd be able to handle bizzarre inputs, non-numbers, etc. gracefully without throwing an exception or calling abort() in a panic. This isn't a huge priority *now*, but will be more important later when the parser will be dealing with numbers from the user.

**Comment by PracticalMetal** [comment]
Hi, I would like to work on this, can you suggest me ways to get started?

**Comment by Gravecat** [comment]
Sure thing, @PracticalMetal! The issue resides within [core/parser.cpp](https://github.com/Gravecat/Greave/blob/main/src/core/parser.cpp), on what is currently line 342, which goes:

`else ActionCheat::add_money(std::stol(words.at(0)));`

The problem being, `std::stol()` does not take kindly to being given ridiculously large numbers (e.g. something higher than INT_MAX, or 2,147,483,647.) So when the player enters a number higher than that into the `#money` command (e.g. `#money 9999999999`), std::stol() aborts because it was given invalid input.

I think the best way to handle this would be to write a separate function (probably in [core/strx.cpp](https://github.com/Gravecat/Greave/blob/main/src/core/strx.cpp) where all the string-related utility functions reside) that handles conversion from a string to an integer *without* aborting when being given an unreasonable number.

Effectively, what we need here is a drop-in replacement that *acts* like `std::stol()`, but handles very very large numbers more gracefully. Possibly the simplest solution would be a wrapper function that takes the number-as-a-string, verifies that it's valid (within the bounds of INT_MAX), and if so, hands it off to `std::stol()`. If not, it'd just return `INT_MAX`.

**Comment by PracticalMetal** [comment]
I understood the issue and I am working on it.

**Comment by Gravecat** [comment]
Looks like that did the trick! Thanks for the contribution! :)
